local map = vim.keymap.set

map("i", "jk", "<ESC>", { desc = "Exit insert mode", nowait = true })
map("i", "<C-h>", "<Left>", { desc = "Move left" })
map("i", "<C-l>", "<Right>", { desc = "Move right" })
map("i", "<C-k>", "<Up>", { desc = "Move up" })
map("i", "<C-j>", "<Down>", { desc = "Move down" })
map("i", "<C-b>", "<ESC><S-i>", { desc = "Insert mode at beginning of char" })
map("i", "<C-e>", "<ESC><S-a>", { desc = "Insert mode at end of char" })
map("n", "<C-d", "<C-d>zz", { desc = "Jump half page down and keep cursor centered" })
map("n", "<C-u", "<C-u>zz", { desc = "Jump half page up and keep cursor centered" })
map("n", "n", "nzzzv", { desc = "Keep cursor centered when moving to next search result" })
map("n", "N", "Nzzzv", { desc = "Keep cursor centered when moving to previous search result" })
map("n", "<M-o>", '@="m`o<C-V><Esc>``"<CR>', { desc = "Insert newline below", silent = true })
map("n", "<M-O>", '@="m`O<C-V><Esc>``"<CR>', { desc = "Insert newline above", silent = true })
